<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#4652d4"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><title>RedVecinal Vecinos</title><link rel="manifest" href="manifest.json"><link rel="apple-touch-icon" href="<?= url('public/assets/img/icon-192.png') ?>"><link rel="stylesheet" href="<?= url('public/assets/css/bootstrap.min.css') ?>"><link rel="stylesheet" href="<?= url('vecinos/assets/vecinos.css') ?>"></head><body>
<header class="neighbor-topbar"><a class="neighbor-brand" href="<?= url('vecinos/') ?>"><span>RV</span><div><strong>RedVecinal</strong><small>Vecinos</small></div></a><div class="neighbor-context"><span class="online-dot"></span><div><small>Comuna activa</small><strong><?= e($user['commune_name']??'Mi comunidad') ?></strong></div></div><button class="install-neighbor" data-install-neighbor hidden>Instalar</button><form method="post" action="<?= url('salir') ?>"><?= csrf_field() ?><button class="logout-neighbor" aria-label="Cerrar sesión">Salir</button></form></header>
<main class="neighbor-shell">
<?php if($flash):?><div class="neighbor-flash"><?= e($flash) ?></div><?php endif;?>
<?php if($page==='inicio'):?>
<section class="neighbor-greeting"><div><span>MI RED VECINAL</span><h1>Hola, <?= e(explode(' ',$user['name'])[0]) ?></h1><p>Revisa tu comunidad y accede rápidamente a las funciones de seguridad.</p></div><a href="?page=reportar">Nueva denuncia</a></section>
<section class="neighbor-panic"><div><span class="panic-symbol">!</span><div><small>RESPUESTA RÁPIDA</small><h2>Botón de pánico</h2><p>Comparte tu ubicación y envía una alerta crítica a la central.</p></div></div><button data-neighbor-panic><strong>MANTENER 2 SEGUNDOS</strong><small>Solo ante una emergencia real</small></button><p data-panic-message>En riesgo vital también debes llamar al 133, 132 o 131.</p></section>
<section class="neighbor-quick-grid"><a href="?page=reportar"><span class="quick-coral">+</span><strong>Denunciar</strong><small>Seguridad o barrio</small></a><a href="?page=reportes"><span class="quick-blue">◎</span><strong>Mis reportes</strong><small><?= $stats['active'] ?> en seguimiento</small></a><a href="?page=mascotas"><span class="quick-yellow">♡</span><strong>Mascotas</strong><small><?= $stats['pets'] ?> registradas</small></a><a href="?page=seguridad"><span class="quick-green">⌂</span><strong>Mi seguridad</strong><small><?= $stats['devices'] ?> dispositivos</small></a></section>
<div class="neighbor-dashboard-grid"><section class="neighbor-card"><div class="neighbor-card-head"><div><small>ACTIVIDAD</small><h2>Reportes recientes</h2></div><a href="?page=reportes">Ver todos</a></div><div class="neighbor-list"><?php if(!$reports):?><div class="neighbor-empty">Aún no tienes denuncias registradas.</div><?php endif;?><?php foreach(array_slice($reports,0,5) as $report):?><a href="?page=reportes"><i style="--item-color:<?= e($report['color']) ?>"><?= e(mb_strtoupper(mb_substr($report['type_name'],0,1))) ?></i><div><strong><?= e($report['title']) ?></strong><small><?= e($report['public_code']) ?> · <?= e(date('d/m H:i',strtotime($report['created_at']))) ?></small></div><b class="status-<?= e($report['status']) ?>"><?= e(str_replace('_',' ',$report['status'])) ?></b></a><?php endforeach;?></div></section><section class="neighbor-card emergency-card"><div class="neighbor-card-head"><div><small>AYUDA DIRECTA</small><h2>Emergencias</h2></div></div><?php foreach(array_slice($contacts,0,5) as $contact):?><a href="tel:<?= e(preg_replace('/[^0-9+]/','',$contact['phone'])) ?>"><span><strong><?= e($contact['service']) ?></strong><small><?= e($contact['name']) ?></small></span><b><?= e($contact['phone']) ?></b></a><?php endforeach;?></section></div>
<?php elseif($page==='reportar'):?>
<section class="neighbor-page-head"><a href="?page=inicio">← Inicio</a><span>NUEVA DENUNCIA</span><h1>¿Qué está ocurriendo?</h1><p>Agrega información clara y tu ubicación para facilitar la respuesta.</p></section><form class="neighbor-form" method="post" action="?action=report"><?= csrf_field() ?><fieldset><legend>Tipo de reporte</legend><div class="neighbor-type-grid"><?php foreach($types as $type):?><label><input type="radio" name="report_type_id" value="<?= (int)$type['id'] ?>" data-priority="<?= e($type['priority_default']) ?>" required><span style="--type:<?= e($type['color']) ?>"><i><?= e(mb_strtoupper(mb_substr($type['name'],0,1))) ?></i><strong><?= e($type['name']) ?></strong></span></label><?php endforeach;?></div></fieldset><fieldset><legend>Información del hecho</legend><div class="form-grid"><label class="wide">Título breve<input name="title" maxlength="160" required placeholder="Ej.: Vehículo sospechoso en la plaza"></label><label>Prioridad<select name="priority" id="neighborPriority"><option value="baja">Baja</option><option value="media" selected>Media</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></label><label class="wide">Descripción<textarea name="description" required rows="4" placeholder="Describe lo ocurrido y referencias útiles"></textarea></label><label>Dirección<input name="address" value="<?= e($user['address']??'') ?>"></label><label>Sector<select name="sector_id"><option value="">Sin sector</option><?php foreach($sectors as $sector):?><option value="<?= (int)$sector['id'] ?>" <?= (int)$user['sector_id']===(int)$sector['id']?'selected':'' ?>><?= e($sector['name']) ?></option><?php endforeach;?></select></label><input type="hidden" name="latitude"><input type="hidden" name="longitude"><button type="button" class="location-button wide" data-neighbor-location>Usar mi ubicación actual</button></div></fieldset><label class="neighbor-check"><input type="checkbox" name="is_anonymous" value="1"> Ocultar mi nombre frente a otros vecinos</label><button class="primary-submit">Enviar denuncia</button></form>
<?php elseif($page==='reportes'):?>
<section class="neighbor-page-head"><a href="?page=inicio">← Inicio</a><span>SEGUIMIENTO</span><h1>Mis reportes</h1><p>Consulta el estado de todas tus denuncias.</p></section><div class="neighbor-report-grid"><?php if(!$reports):?><div class="neighbor-empty">No tienes reportes registrados.</div><?php endif;?><?php foreach($reports as $report):?><article><header><i style="--item-color:<?= e($report['color']) ?>"><?= e(mb_strtoupper(mb_substr($report['type_name'],0,1))) ?></i><div><small><?= e($report['public_code']) ?></small><h2><?= e($report['title']) ?></h2></div><b class="status-<?= e($report['status']) ?>"><?= e(str_replace('_',' ',$report['status'])) ?></b></header><p><?= e(mb_strimwidth($report['description'],0,180,'…')) ?></p><footer><span><?= e($report['address']?:'Sin dirección') ?></span><time><?= e(date('d/m/Y H:i',strtotime($report['created_at']))) ?></time></footer></article><?php endforeach;?></div>
<?php elseif($page==='mascotas'):?>
<section class="neighbor-page-head"><a href="?page=inicio">← Inicio</a><span>IDENTIFICACIÓN Y BÚSQUEDA</span><h1>Mis mascotas</h1><p>Registra sus datos, cambia su estado y genera una credencial QR para el collar.</p></section>
<div class="neighbor-two-columns pet-module-layout">
  <div class="neighbor-pet-grid modern-pet-grid">
    <?php if(!$pets):?><div class="neighbor-empty">No tienes mascotas registradas.</div><?php endif;?>
    <?php foreach($pets as $pet):?><article class="modern-pet-card">
      <div class="pet-card-top"><span class="pet-avatar-letter"><?= e(mb_strtoupper(mb_substr($pet['name'],0,1))) ?></span><div><small><?= e($pet['species']) ?></small><h2><?= e($pet['name']) ?></h2><p><?= e($pet['breed']?:'Sin raza informada') ?><?= $pet['color']?' · '.e($pet['color']):'' ?></p></div><b class="pet-<?= e($pet['status']) ?>"><?= e(str_replace('_',' ',$pet['status'])) ?></b></div>
      <?php if($pet['description']):?><p class="pet-description-short"><?= e(mb_strimwidth($pet['description'],0,100,'…')) ?></p><?php endif;?>
      <div class="pet-card-actions"><a class="pet-credential-link" target="_blank" href="<?= url('mascotas/'.$pet['id'].'/credencial') ?>"><span>QR</span><div><strong>Credencial para imprimir</strong><small>Carnet y colgante PDF</small></div></a><a class="pet-profile-link" target="_blank" href="<?= url('mascota/qr/'.$pet['qr_token']) ?>">Ver ficha pública ↗</a></div>
      <form class="pet-status-form" method="post" action="?action=pet_status"><?= csrf_field() ?><input type="hidden" name="pet_id" value="<?= (int)$pet['id'] ?>"><select name="status" aria-label="Estado de <?= e($pet['name']) ?>"><option value="en_casa" <?= $pet['status']==='en_casa'?'selected':'' ?>>En casa</option><option value="perdida" <?= $pet['status']==='perdida'?'selected':'' ?>>Perdida</option><option value="encontrada" <?= $pet['status']==='encontrada'?'selected':'' ?>>Encontrada</option></select><input name="last_seen_address" value="<?= e($pet['last_seen_address']??'') ?>" placeholder="Último lugar visto"><button>Actualizar</button></form>
    </article><?php endforeach;?>
  </div>
  <form class="neighbor-form compact-form pet-register-form" method="post" action="?action=pet"><?= csrf_field() ?><div class="compact-form-heading"><span>NUEVA CREDENCIAL</span><h2>Registrar mascota</h2><p>Al guardar se abrirá su tarjeta QR lista para imprimir.</p></div><div class="pet-form-grid"><label>Nombre<input name="name" required></label><label>Tipo<select name="species" required><option value="">Seleccionar</option><option>Perro</option><option>Gato</option><option>Ave</option><option>Otra</option></select></label><label>Raza<input name="breed"></label><label>Color<input name="color"></label><label class="wide">Señas particulares<textarea name="description" rows="3" placeholder="Manchas, collar, características..."></textarea></label><label>Estado<select name="status"><option value="en_casa">En casa</option><option value="perdida">Perdida</option><option value="encontrada">Encontrada</option></select></label><label>Último lugar visto<input name="last_seen_address"></label></div><button class="primary-submit">Guardar y crear credencial QR</button></form>
</div>
<?php elseif($page==='seguridad'):?>
<section class="neighbor-page-head"><a href="?page=inicio">← Inicio</a><span>HOGAR CONECTADO</span><h1>Mi seguridad</h1><p>Administra cámaras, alarmas, sensores y botones de pánico del hogar.</p></section><div class="neighbor-two-columns"><div class="neighbor-device-grid"><?php if(!$devices):?><div class="neighbor-empty">No tienes dispositivos registrados.</div><?php endif;?><?php foreach($devices as $device):?><article><span>⌂</span><div><h2><?= e($device['name']) ?></h2><p><?= e(str_replace('_',' ',$device['type'])) ?> · <?= e($device['location']?:'Sin ubicación') ?></p><b><?= e(str_replace('_',' ',$device['status'])) ?></b></div></article><?php endforeach;?></div><form class="neighbor-form compact-form" method="post" action="?action=device"><?= csrf_field() ?><h2>Agregar dispositivo</h2><label>Nombre<input name="name" placeholder="Cámara acceso principal" required></label><label>Tipo<select name="type"><option value="camara">Cámara</option><option value="alarma">Alarma</option><option value="sensor">Sensor</option><option value="boton_panico">Botón de pánico</option><option value="otro">Otro</option></select></label><label>Ubicación<input name="location" placeholder="Entrada, patio..."></label><label>URL de conexión<input name="connection_url" placeholder="Opcional"></label><button class="primary-submit">Guardar dispositivo</button></form></div>
<?php else:?>
<section class="neighbor-page-head"><a href="?page=inicio">← Inicio</a><span>DATOS DE SEGURIDAD</span><h1>Mi perfil</h1><p>Mantén actualizados tus datos para recibir ayuda con rapidez.</p></section><form class="neighbor-form profile-form" method="post" action="?action=profile"><?= csrf_field() ?><fieldset><legend>Datos de contacto</legend><div class="form-grid"><label>Nombre<input value="<?= e($user['name']) ?>" disabled></label><label>RUT<input value="<?= e($user['rut']??'') ?>" disabled></label><label>Teléfono<input name="phone" value="<?= e($user['phone']??'') ?>" required></label><label class="wide">Dirección<input name="address" value="<?= e($user['address']??'') ?>" required></label><label>Sector<select name="sector_id"><option value="">Sin sector</option><?php foreach($sectors as $sector):?><option value="<?= (int)$sector['id'] ?>" <?= (int)$user['sector_id']===(int)$sector['id']?'selected':'' ?>><?= e($sector['name']) ?></option><?php endforeach;?></select></label></div></fieldset><fieldset><legend>Contacto de emergencia</legend><div class="form-grid"><label>Nombre<input name="emergency_name" value="<?= e($securityContact['name']??'') ?>" required></label><label>Relación<input name="emergency_relationship" value="<?= e($securityContact['relationship']??'') ?>" required></label><label>Teléfono<input name="emergency_phone" value="<?= e($securityContact['phone']??'') ?>" required></label></div></fieldset><button class="primary-submit">Actualizar ficha de seguridad</button></form>
<?php endif;?>
</main><nav class="neighbor-bottom"><a class="<?= $page==='inicio'?'active':'' ?>" href="?page=inicio"><i>⌂</i><span>Inicio</span></a><a class="<?= $page==='reportar'?'active':'' ?>" href="?page=reportar"><i>+</i><span>Denunciar</span></a><a class="<?= $page==='reportes'?'active':'' ?>" href="?page=reportes"><i>◎</i><span>Reportes</span></a><a class="<?= $page==='mascotas'?'active':'' ?>" href="?page=mascotas"><i>♡</i><span>Mascotas</span></a><a class="<?= in_array($page,['seguridad','perfil'],true)?'active':'' ?>" href="?page=perfil"><i>●</i><span>Perfil</span></a></nav>
<script>window.NEIGHBOR_APP={base:<?= json_encode(rtrim(url('vecinos/'),'/')) ?>,csrf:<?= json_encode(\App\Core\Csrf::token()) ?>};</script><script src="<?= url('vecinos/assets/vecinos.js') ?>"></script></body></html>
