<section class="neighbor-download-hero">
  <div class="container neighbor-hero-grid">
    <div class="neighbor-hero-copy"><span class="eyebrow">REDVECINAL PARA VECINOS</span><h1>Tu seguridad y tu comunidad, siempre contigo</h1><p>Instala la aplicación en tu celular para enviar denuncias geolocalizadas, activar alertas de pánico y seguir la respuesta de tu comuna.</p><div class="neighbor-hero-actions"><a class="btn btn-danger btn-lg" href="#registro">Crear cuenta vecinal</a><button class="btn btn-light btn-lg" data-install-app hidden>Instalar aplicación</button><a class="btn btn-outline-light btn-lg" href="<?= url('ingresar') ?>">Ya tengo cuenta</a></div><div class="neighbor-trust"><span>✓ Instalación gratuita</span><span>✓ Funciona sin conexión</span><span>✓ Datos protegidos</span></div></div>
    <div class="neighbor-phone"><div class="neighbor-phone-top"><span>9:41</span><b>RedVecinal</b><i></i></div><div class="neighbor-phone-body"><span class="mini-label">MI COMUNIDAD</span><h2>Hola, vecino</h2><div class="phone-panic"><span>!</span><strong>Botón de pánico</strong><small>Alerta crítica con ubicación</small></div><div class="phone-actions"><i>Denunciar</i><i>Reportes</i><i>Mascotas</i><i>Seguridad</i></div><div class="phone-case"><span></span><div><strong>Luminaria apagada</strong><small>En proceso · Hace 12 min</small></div></div></div></div>
  </div>
</section>

<section class="container neighbor-benefits"><div class="section-heading"><span class="eyebrow text-primary">UNA APP PARA TU BARRIO</span><h2>Funciones pensadas para la seguridad vecinal</h2><p>Acceso rápido, formularios claros y seguimiento desde cualquier teléfono.</p></div><div class="neighbor-benefit-grid"><article><?= svg_icon('alert') ?><h3>Denuncias geolocalizadas</h3><p>Informa robos, emergencias y problemas urbanos con ubicación y evidencia.</p></article><article><?= svg_icon('shield') ?><h3>Alerta de pánico</h3><p>Activa una alerta crítica mediante pulsación prolongada para evitar envíos accidentales.</p></article><article><?= svg_icon('history') ?><h3>Seguimiento</h3><p>Revisa el estado de tus denuncias y las respuestas de la central comunal.</p></article><article><?= svg_icon('paw') ?><h3>Ayuda comunitaria</h3><p>Gestiona mascotas perdidas, contactos de emergencia y dispositivos del hogar.</p></article></div></section>

<section class="neighbor-register-section" id="registro"><div class="container neighbor-register-grid"><div class="neighbor-register-copy"><span class="eyebrow">REGISTRO SEGURO</span><h2>Crea tu cuenta de vecino</h2><p>Estos datos permiten asociar correctamente tus alertas con tu comuna y entregar información útil a los operadores cuando solicites ayuda.</p><ul><li>Tu RUT evita registros duplicados.</li><li>La dirección y sector facilitan la respuesta.</li><li>El contacto de emergencia solo se utiliza ante incidentes asociados a tu cuenta.</li></ul><div class="privacy-note"><?= svg_icon('shield') ?><span><strong>Información protegida</strong><small>No solicitamos antecedentes médicos ni datos innecesarios.</small></span></div></div>
  <form class="neighbor-register-form" method="post" action="<?= url('vecinos/registro') ?>"><?= csrf_field() ?><div class="form-heading"><span>PASO ÚNICO</span><h2>Datos personales y de seguridad</h2><p>Completa todos los campos obligatorios.</p></div>
    <fieldset><legend>Identificación</legend><div class="row g-3"><div class="col-md-7"><label class="form-label">Nombre completo *</label><input class="form-control" name="name" value="<?= e(old('name')) ?>" autocomplete="name" required></div><div class="col-md-5"><label class="form-label">RUT *</label><input class="form-control" name="rut" value="<?= e(old('rut')) ?>" placeholder="12.345.678-5" required></div><div class="col-md-6"><label class="form-label">Correo electrónico *</label><input type="email" class="form-control" name="email" value="<?= e(old('email')) ?>" autocomplete="email" required></div><div class="col-md-6"><label class="form-label">Teléfono móvil *</label><input type="tel" class="form-control" name="phone" value="<?= e(old('phone')) ?>" placeholder="+56 9 1234 5678" autocomplete="tel" required></div></div></fieldset>
    <fieldset><legend>Domicilio y cobertura</legend><div class="row g-3"><div class="col-md-6"><label class="form-label">Comuna *</label><select class="form-select" name="commune_id" data-neighbor-commune required><option value="">Seleccionar comuna</option><?php foreach($communes as $commune): ?><option value="<?= (int)$commune['id'] ?>" <?= (string)old('commune_id')===(string)$commune['id']?'selected':'' ?>><?= e($commune['name']) ?> · <?= e($commune['region']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Sector o villa</label><select class="form-select" name="sector_id" data-neighbor-sector><option value="">Sin sector definido</option><?php foreach($sectors as $sector): ?><option value="<?= (int)$sector['id'] ?>" data-commune="<?= (int)$sector['commune_id'] ?>" <?= (string)old('sector_id')===(string)$sector['id']?'selected':'' ?>><?= e($sector['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Dirección completa *</label><input class="form-control" name="address" value="<?= e(old('address')) ?>" placeholder="Calle, número, villa o referencia" autocomplete="street-address" required></div></div></fieldset>
    <fieldset><legend>Contacto de emergencia</legend><div class="row g-3"><div class="col-md-5"><label class="form-label">Nombre *</label><input class="form-control" name="emergency_name" value="<?= e(old('emergency_name')) ?>" required></div><div class="col-md-3"><label class="form-label">Relación *</label><input class="form-control" name="emergency_relationship" value="<?= e(old('emergency_relationship')) ?>" placeholder="Familiar" required></div><div class="col-md-4"><label class="form-label">Teléfono *</label><input type="tel" class="form-control" name="emergency_phone" value="<?= e(old('emergency_phone')) ?>" placeholder="+56 9..." required></div></div></fieldset>
    <fieldset><legend>Acceso a la aplicación</legend><div class="row g-3"><div class="col-md-6"><label class="form-label">Contraseña *</label><input type="password" minlength="8" class="form-control" name="password" autocomplete="new-password" required><small>Mínimo 8 caracteres.</small></div><div class="col-md-6"><label class="form-label">Confirmar contraseña *</label><input type="password" minlength="8" class="form-control" name="password_confirmation" autocomplete="new-password" required></div></div></fieldset>
    <label class="neighbor-consent"><input type="checkbox" name="terms" value="1" required><span>Confirmo que los datos ingresados son correctos y autorizo su uso para gestionar alertas y emergencias asociadas a mi cuenta.</span></label><button class="btn btn-danger btn-lg w-100">Crear cuenta e ingresar a la app</button><p class="form-login">¿Ya estás registrado? <a href="<?= url('ingresar') ?>">Ingresar a RedVecinal</a></p>
  </form>
</div></section>
