<div class="admin-toolbar">
  <div><span class="section-kicker">CONFIGURACIÓN TERRITORIAL</span><h2>Comunas y sectores</h2><p>Organiza la cobertura territorial utilizada por reportes, vecinos y operadores.</p></div>
  <div class="toolbar-actions"><button class="btn btn-outline-primary" data-modal-open="sectorModal"><?= svg_icon('plus') ?> Nuevo sector</button><button class="btn btn-primary" data-modal-open="communeModal"><?= svg_icon('plus') ?> Nueva comuna</button></div>
</div>

<div class="admin-columns">
  <section class="card panel-card table-card">
    <div class="card-header"><div><span class="card-eyebrow">COBERTURA</span><h2>Comunas registradas</h2><p><?= count($communes) ?> territorios configurados</p></div></div>
    <div class="table-responsive"><table class="table admin-table"><thead><tr><th>Comuna</th><th>Región</th><th>Usuarios</th><th>Sectores</th></tr></thead><tbody><?php foreach($communes as $commune): ?><tr><td><div class="territory-cell"><span><?= svg_icon('map') ?></span><strong><?= e($commune['name']) ?></strong></div></td><td><span class="cell-muted"><?= e($commune['region']) ?></span></td><td><span class="count-chip"><?= $commune['users_count'] ?></span></td><td><span class="count-chip"><?= $commune['sectors_count'] ?></span></td></tr><?php endforeach; ?></tbody></table></div>
  </section>
  <section class="card panel-card table-card">
    <div class="card-header"><div><span class="card-eyebrow">SUBDIVISIONES</span><h2>Sectores vecinales</h2><p><?= count($sectors) ?> sectores registrados</p></div></div>
    <div class="table-responsive"><table class="table admin-table"><thead><tr><th>Sector</th><th>Comuna</th><th>Estado</th></tr></thead><tbody><?php if(!$sectors): ?><tr><td colspan="3" class="empty-state compact">Aún no hay sectores creados.</td></tr><?php endif; ?><?php foreach($sectors as $sector): ?><tr><td><strong class="cell-primary"><?= e($sector['name']) ?></strong></td><td><span class="cell-muted"><?= e($sector['commune_name']) ?></span></td><td><span class="status-pill status-<?= e($sector['status']) ?>"><i></i><?= e($sector['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div>
  </section>
</div>

<div class="modal" id="communeModal" hidden><div class="modal-dialog modal-dialog-sm"><div class="modal-content"><div class="modal-header"><div><span class="section-kicker">TERRITORIO</span><h2>Nueva comuna</h2><p>Agrega una nueva cobertura administrativa.</p></div><button data-modal-close>×</button></div><form method="post" action="<?= url('administracion/comunas') ?>"><?= csrf_field() ?><div class="modal-body"><div class="form-stack"><div><label class="form-label">Nombre de la comuna <em>*</em></label><input class="form-control" name="name" required></div><div><label class="form-label">Región <em>*</em></label><input class="form-control" name="region" placeholder="Ej.: Región del Biobío" required></div><div><label class="form-label">Código territorial</label><input class="form-control" name="code" placeholder="Opcional"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary">Guardar comuna</button></div></form></div></div></div>
<div class="modal" id="sectorModal" hidden><div class="modal-dialog modal-dialog-sm"><div class="modal-content"><div class="modal-header"><div><span class="section-kicker">ORGANIZACIÓN</span><h2>Nuevo sector</h2><p>Asocia el sector a una comuna existente.</p></div><button data-modal-close>×</button></div><form method="post" action="<?= url('administracion/sectores') ?>"><?= csrf_field() ?><div class="modal-body"><div class="form-stack"><div><label class="form-label">Comuna <em>*</em></label><select class="form-select" name="commune_id"><?php foreach($communes as $commune): ?><option value="<?= $commune['id'] ?>"><?= e($commune['name']) ?></option><?php endforeach; ?></select></div><div><label class="form-label">Nombre del sector <em>*</em></label><input class="form-control" name="name" placeholder="Ej.: Villa España" required></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary">Guardar sector</button></div></form></div></div></div>

