<div class="admin-toolbar">
  <div><span class="section-kicker">PREFERENCIAS DEL SISTEMA</span><h2>Configuración comunal</h2><p>Personaliza la identidad, comunicación y comportamiento operativo de RedVecinal.</p></div>
</div>

<div class="settings-layout">
  <form class="card panel-card settings-form" method="post" action="<?= url('administracion/configuracion') ?>">
    <?= csrf_field() ?>
    <div class="card-header"><div><span class="card-eyebrow">DATOS GENERALES</span><h2>Identidad y contacto municipal</h2><p>Información visible para operadores y vecinos.</p></div></div>
    <div class="card-body">
      <div class="form-section"><h3>Organización</h3><div class="row g-3"><div class="col-md-6"><label class="form-label">Nombre de la organización</label><input class="form-control" name="organization_name" value="<?= e($settings['organization_name']) ?>" required></div><div class="col-md-6"><label class="form-label">Teléfono municipal</label><input class="form-control" name="municipal_phone" value="<?= e($settings['municipal_phone']) ?>" placeholder="+56 43..."></div><div class="col-md-6"><label class="form-label">Correo institucional</label><input type="email" class="form-control" name="municipal_email" value="<?= e($settings['municipal_email']) ?>" placeholder="seguridad@municipio.cl"></div><div class="col-md-6"><label class="form-label">Dirección</label><input class="form-control" name="municipal_address" value="<?= e($settings['municipal_address']) ?>"></div></div></div>
      <div class="form-section map-settings-section"><div class="form-section-title"><div><h3>Mapa comunal</h3><p>Selecciona una comuna y RedVecinal ubicará automáticamente el centro del mapa.</p></div><span class="map-location-state" data-map-geocode-status>Ubicación configurada</span></div><div class="row g-3 align-items-end"><div class="col-md-9"><label class="form-label">Comuna mostrada en el dashboard</label><select class="form-select" name="map_commune_id" data-map-commune-select required><option value="">Selecciona una comuna</option><?php foreach($communes as $commune): ?><option value="<?= (int)$commune['id'] ?>" data-name="<?= e($commune['name']) ?>" data-region="<?= e($commune['region']) ?>" <?= (int)$settings['map_commune_id']===(int)$commune['id']?'selected':'' ?>><?= e($commune['name']) ?> · <?= e($commune['region']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Nivel de detalle</label><select class="form-select" name="map_zoom"><option value="11" <?= $settings['map_zoom']==='11'?'selected':'' ?>>Amplio</option><option value="13" <?= $settings['map_zoom']==='13'?'selected':'' ?>>Comunal</option><option value="15" <?= $settings['map_zoom']==='15'?'selected':'' ?>>Barrial</option><option value="17" <?= $settings['map_zoom']==='17'?'selected':'' ?>>Cercano</option></select></div></div><input type="hidden" name="map_center_lat" value="<?= e($settings['map_center_lat']) ?>"><input type="hidden" name="map_center_lng" value="<?= e($settings['map_center_lng']) ?>"><div id="settingsMapPreview" class="settings-map-preview" aria-label="Vista previa del mapa configurado"></div><small class="form-text">La ubicación se obtiene desde OpenStreetMap. Puedes guardar cuando aparezca la confirmación verde.</small></div>
      <div class="form-section"><h3>Operación y privacidad</h3><div class="settings-switches"><label class="setting-switch"><span><strong>Permitir reportes anónimos</strong><small>Los operadores siempre podrán identificar al emisor.</small></span><input type="checkbox" name="reports_anonymous" value="1" <?= $settings['reports_anonymous']==='1'?'checked':'' ?>><i></i></label><label class="setting-switch"><span><strong>Notificaciones internas</strong><small>Avisar a operadores cuando se recibe un nuevo reporte.</small></span><input type="checkbox" name="notifications_enabled" value="1" <?= $settings['notifications_enabled']==='1'?'checked':'' ?>><i></i></label><label class="setting-switch"><span><strong>Alertas de dispositivos</strong><small>Procesar eventos críticos enviados por cámaras y alarmas.</small></span><input type="checkbox" name="device_alerts_enabled" value="1" <?= $settings['device_alerts_enabled']==='1'?'checked':'' ?>><i></i></label></div><div class="retention-field"><label class="form-label">Retención de reportes</label><div><input type="number" min="30" max="3650" class="form-control" name="report_retention_days" value="<?= e($settings['report_retention_days']) ?>"><span>días</span></div><small>Define cuánto tiempo conservar información histórica.</small></div></div>
    </div>
    <div class="card-footer settings-footer"><span>Los cambios se aplican a la comuna activa.</span><button class="btn btn-primary"><?= svg_icon('check') ?> Guardar configuración</button></div>
  </form>

  <aside class="settings-side">
    <section class="card panel-card"><div class="card-header"><div><span class="card-eyebrow">RESPUESTA RÁPIDA</span><h2>Contactos de emergencia</h2><p>Teléfonos visibles en el panel.</p></div><button class="btn btn-outline-primary btn-sm" data-modal-open="contactModal"><?= svg_icon('plus') ?> Agregar</button></div><div class="settings-contacts">
      <?php foreach($contacts as $contact): ?><div class="settings-contact"><span class="contact-icon"><?= svg_icon('alert') ?></span><div><strong><?= e($contact['service']) ?></strong><small><?= e($contact['name']) ?> · <?= e($contact['phone']) ?></small></div><?php if($contact['commune_id']): ?><form method="post" action="<?= url('administracion/contactos/'.$contact['id'].'/estado') ?>"><?= csrf_field() ?><input type="hidden" name="active" value="<?= $contact['active']?'0':'1' ?>"><button class="status-toggle <?= $contact['active']?'active':'' ?>" title="<?= $contact['active']?'Desactivar':'Activar' ?>"><i></i></button></form><?php else: ?><span class="national-chip">Nacional</span><?php endif; ?></div><?php endforeach; ?>
    </div></section>
    <section class="notice-card mt-3"><?= svg_icon('shield') ?><div><strong>Configuración auditada</strong><p>Cada cambio queda registrado en el módulo de auditoría con fecha, usuario e información modificada.</p></div></section>
  </aside>
</div>

<div class="modal" id="contactModal" hidden><div class="modal-dialog modal-dialog-sm"><div class="modal-content"><div class="modal-header"><div><span class="section-kicker">EMERGENCIAS</span><h2>Nuevo contacto</h2><p>Agrega un servicio disponible para la comuna.</p></div><button data-modal-close>×</button></div><form method="post" action="<?= url('administracion/contactos') ?>"><?= csrf_field() ?><div class="modal-body"><div class="form-stack"><div><label class="form-label">Nombre de la institución</label><input class="form-control" name="name" placeholder="Ej.: Seguridad Ciudadana" required></div><div><label class="form-label">Tipo de servicio</label><input class="form-control" name="service" placeholder="Ej.: Patrullaje municipal" required></div><div><label class="form-label">Teléfono</label><input class="form-control" name="phone" placeholder="Ej.: 432000000" required></div><label class="form-check"><input type="checkbox" class="form-check-input" name="available_24h" value="1"><span>Disponible las 24 horas</span></label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-modal-close>Cancelar</button><button class="btn btn-primary">Guardar contacto</button></div></form></div></div></div>
