<?php $currentUser=auth();$message=flash('message');$messageType=flash('type','success'); ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#174f45"><meta name="csrf-token" content="<?= e(\App\Core\Csrf::token()) ?>"><title><?= e($title??'RedVecinal') ?> | RedVecinal</title><link rel="manifest" href="<?= url('public/manifest.json') ?>"><link rel="stylesheet" href="<?= asset('css/bootstrap.min.css') ?>"><link rel="stylesheet" href="<?= asset('css/app.css') ?>"></head>
<body class="<?= !empty($publicPage)?'public-body':'app-body' ?>"><div id="offlineBanner" class="offline-banner" hidden>Sin conexión: tus nuevos reportes quedarán guardados para enviarse después.</div>
<?php if($currentUser): ?><aside class="sidebar" id="sidebar"><a class="brand" href="<?= url('panel') ?>"><span class="brand-symbol">RV</span><span>RedVecinal<small>Comunidad conectada</small></span></a><nav class="side-nav">
<a class="<?= active('panel') ?>" href="<?= url('panel') ?>">⌂ <span>Panel</span></a><a class="<?= active('reportes') ?>" href="<?= url('reportes') ?>">⚠ <span>Reportes</span></a><a class="<?= active('mascotas') ?>" href="<?= url('mascotas') ?>">♡ <span>Mascotas</span></a><a class="<?= active('dispositivos') ?>" href="<?= url('dispositivos') ?>">◉ <span>Dispositivos</span></a>
<?php if(can('users.manage')||can('communes.manage')||can('roles.manage')): ?><div class="nav-label">Administración</div><?php if(can('users.manage')):?><a class="<?= active('administracion/usuarios') ?>" href="<?= url('administracion/usuarios') ?>">♙ <span>Usuarios</span></a><?php endif; ?><?php if(can('communes.manage')):?><a class="<?= active('administracion/comunas') ?>" href="<?= url('administracion/comunas') ?>">◎ <span>Comunas</span></a><?php endif; ?><?php if(can('roles.manage')):?><a class="<?= active('administracion/roles') ?>" href="<?= url('administracion/roles') ?>">⌘ <span>Roles</span></a><?php endif; ?><?php endif; ?>
</nav><div class="sidebar-user"><div class="avatar"><?= e(mb_strtoupper(mb_substr($currentUser['name'],0,1))) ?></div><div><strong><?= e($currentUser['name']) ?></strong><small><?= e($currentUser['role_name']) ?></small></div></div></aside>
<div class="app-main"><header class="topbar"><button class="menu-button" data-sidebar-toggle aria-label="Abrir menú">☰</button><div><h1><?= e($title??'Panel') ?></h1><small><?= e($currentUser['commune_name']??'RedVecinal') ?></small></div><div class="top-actions"><a class="btn btn-danger btn-sm" href="<?= url('reportes/nuevo') ?>">+ Reportar</a><form method="post" action="<?= url('salir') ?>"><?= csrf_field() ?><button class="btn btn-outline-secondary btn-sm">Salir</button></form></div></header><main class="content">
<?php else: ?><header class="public-nav"><div class="container nav-inner"><a class="brand brand-dark" href="<?= url() ?>"><span class="brand-symbol">RV</span><span>RedVecinal</span></a><nav><a href="<?= url('ingresar') ?>">Ingresar</a><a class="btn btn-primary btn-sm" href="<?= url('registro') ?>">Crear cuenta</a></nav></div></header><main>
<?php endif; ?><?php if($message): ?><div class="alert alert-<?= e($messageType) ?> alert-dismissible" role="alert"><?= e($message) ?><button type="button" class="alert-close" data-dismiss-alert>×</button></div><?php endif; ?>

